### ISSUE TITLE
Startup never called with TTS.STARTED

### ISSUE THREAD

**Issue by macdonst** [macdonst/TTS#1]
The plugin starts up eventually and works fine; however, for some reason I am never getting the TTS.STARTED message from the StartupWin callback function. I found out that StartupWin is called twice, first with result == 1 (initializing), and the second time with result == null (2 is expected). I am running Cordova 2.3.0.

**Comment by macdonst** [comment]
Resolved

**Comment by univie** [comment]
After the update I get result == 2, but evaluating if (result == TTS.STARTED) gives reference error "TTS is not defined". Maybe a tts.js issue?

**Comment by macdonst** [comment]
Ug, I forgot to export the constants. I'll fix it soon.

**Comment by jrhames** [comment]
Thanks. I'm also waiting for the constants.

**Comment by macdonst** [comment]
Lastest quick fix puts the constants back.
