### ISSUE TITLE
Callbacks are never called on speak method.

### ISSUE THREAD

**Issue by jrhames** [macdonst/TTS#2]
The tts.speak method works, but it's callbacks are never called (either win or fail).

Example:

``` javascript
window.plugins.tts.speak("Text", function() {
    console.log('speak finish playing.');
}, function() {
    console.log('error occurred.');
});
```

**Comment by macdonst** [comment]
Yeah, for some odd reason the onUtteranceCompleted method is never being fired.

**Comment by jrhames** [comment]
Any ideas on how to solve this one?

**Comment by macdonst** [comment]
I've had no time to look at it. Soon I hope.

**Comment by macdonst** [comment]
Why did you close it?

**Comment by jrhames** [comment]
My bad. I did it by mistake.

**Comment by jrhames** [comment]
So, I tried yesterday replacing the UtteranceCompleteListener by the UtteranceProgressListener without success. I'm still trying to figure out why this is happening. If there's something else you think it's worth a try, let me know. I'm willing to help.

**Comment by macdonst** [comment]
I'm an idiot. I forgot to set the utterance ID. Fixed now.

**Comment by jrhames** [comment]
Well, it's fixed. No harm done. Thanks for you support.
